name: ui test
'on':
  push:
    branches:
      - master

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Installed package list
      run: apt list --installed
    - name: Remove Chrome
      run: sudo apt purge google-chrome-stable
    - name: Remove default Chromium
      run: sudo apt purge chromium-browser
    - name: Install a new Chromium
      run: sudo apt install -y chromium-browser 
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -r ./test/requirements.txt
    - name: Run selenium check
      run: |
        python ./test/test_ui.py
